### ISSUE TITLE
Some small CSS changes.

### ISSUE THREAD

**Issue by stefanheimes** [contao-community-alliance/contao-multicolumnwizard-bundle#67]
We should add some CSS changes for example:

```css
table.tl_modulewizard.multicolumnwizard,
table.tl_modulewizard.multicolumnwizard tr,
table.tl_modulewizard.multicolumnwizard td
{
    width: auto;
    max-width: none;
}

table.tl_modulewizard.multicolumnwizard td {
    padding-right: 10px;
}
```
This will prevent the table to take 100% of the available space. It's a much better look.
